DROP TABLE IF EXISTS comments_likes;
DROP TABLE IF EXISTS posts_likes;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS topics;
DROP TABLE IF EXISTS regions;
